spring.application.name=ProductImageStudio

server.port=8080

# Postgres
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product_image_studio}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# RUNPOD
runpod.base-url=https://api.runpod.ai/v2/
runpod.api-key=${RUNPOD_API_KEY:Dummy}
runpod.endpoint-id=qwen-image-edit-2511-lora